name: Windows RDP (Playit - no new user)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Playit
      run: |
        Invoke-WebRequest ` https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-amd64.exe ` -OutFile playit.exe
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Password for runneradmin
      run: |
        net user runneradmin P@ssw0rd123

    - name: Start Playit Tunnel
      run: |
        Start-Process -NoNewWindow -FilePath ".\playit.exe"

    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -Seconds 60 }
