name: Windows RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip

    - name: Setup Ngrok Auth
      run: .\ngrok\ngrok.exe authtoken 3Ci7aHNpDLky63uRb4buLFSxPNV_34PsL7X1AXjetncKE53vC

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Password
      run: net user runneradmin P@ssw0rd123

    - name: Start Ngrok Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
